### ISSUE TITLE
无法获取apollo配置

### ISSUE THREAD

**Issue by liuguangshun** [zhangxh1023/apollo-node-client#11]
安装 "apollo-node-client": "^1.4.3"，无法正常获取apollo配置， "apollo-node-client"已安装，程序里面有./node_modules/apollo-node-client/dist/lib/access文件，具体错误信息：
Error: Cannot find module './lib/access'
    at webpackEmptyContext (eval at ./node_modules/apollo-node-client/dist sync recursive (testx.js:10:1), <anonymous>:2:10)
    at eval (index.js:29:18)
    at eval (index.js:17:17)
    at eval (index.js:26:3)
    at ./node_modules/apollo-node-client/dist/index.js (testx.js:21:1)
    at __webpack_require__ (app.js:854:30)
    at fn (app.js:151:20)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/testx.vue?vue&type=script&lang=ts:32:5)
    at ./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/testx.vue?vue&type=script&lang=ts (testx.js:709:1)
    at __webpack_require__ (app.js:854:30)

**Comment by zhangxh1023** [comment]
这是在前端项目中引用吗，目前是只支持在Node.js中使用
虽然看起来报错应该是其他的原因。。。可能需要一个可以复现的最小demo才能确定
